Setting:
   # 是否开启礼包上线提示领取
   OnlineReminder: true
   ChackUpdate: true
   Language: 'none'
Default:
   # 默认礼包展示名
   Name: '§6Server Kit'
   # 默认领取次数(-1为不限次数)
   Time: 1
   # 默认冷却时间
   Delay: 60
   # 默认礼包的展示
   Icon: 'CHEST'
   # 上次重置插件或关闭插件的时间
   ShutDate: 'None'
   # 防崩服刷新礼包检查时间,单位：分钟/次(0为不开启)
   AntiShutDown: 5
GUI:
   GetAllMaterial: 'Default'
   TurnPageMaterial: 'SLIME_BALL'
   #菜单栏材质
   MenuMaterial: 'Default'
   # 领取礼包后关闭GUI
   ClickClose: true
NewComer:
   # 是否开启新人礼包
   Enable: true
   # 将指定礼包设定为新人礼包
   Kit: 'NCKit'
   # 是否自动发放
   Auto: true
KitCode:
   # CDK密钥(不要随意改动)
   Key: 'none'
MySQL:
   #是否开启数据库模式
   Enable: false
   # 数据库名字
   databasename: 'name'
   # 用户名
   username: 'user'
   # 密码
   password: 'pw'
   # 端口
   port: '3306'
   # 主机IP
   ip: 'localhost'
Cache:
   Enable: true
   PlayerReciveKit: true